#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path


DASHBOARD_MARKER = "<!-- docs-project-dashboard:generated -->"
DOCS_ROOT_CANDIDATES = ("DOCS", "docs", "documentation")


def find_case_insensitive_dir(parent: Path, name: str) -> Path | None:
    if not parent.exists():
        return None
    for child in parent.iterdir():
        if child.is_dir() and child.name.lower() == name.lower():
            return child
    return None


def score_docs_root(candidate: Path) -> int:
    score = 0
    if find_case_insensitive_dir(candidate, "PROJECTS"):
        score += 10
    if (candidate / "README.md").exists():
        score += 2
    if (candidate / "index.md").exists():
        score += 1
    return score


def discover_docs_root(repo_root: Path, explicit: str | None) -> Path:
    if explicit:
        docs_root = repo_root / explicit
        if not docs_root.is_dir():
            raise FileNotFoundError(f"Docs root not found: {docs_root}")
        return docs_root

    matches = [repo_root / name for name in DOCS_ROOT_CANDIDATES if (repo_root / name).is_dir()]
    if not matches:
        raise FileNotFoundError("Could not find DOCS/, docs/, or documentation/ in the target repo.")

    ranked = sorted((score_docs_root(path), path.name, path) for path in matches)
    best_score, _, best_path = ranked[-1]

    if len(ranked) > 1 and ranked[-2][0] == best_score:
        raise RuntimeError(
            "Multiple docs roots matched with the same score. Re-run with --docs-root to choose one explicitly."
        )

    return best_path


def ensure_projects_root(docs_root: Path) -> Path:
    projects_root = find_case_insensitive_dir(docs_root, "PROJECTS")
    if not projects_root:
        raise FileNotFoundError(
            f"Could not find PROJECTS/ under {docs_root}. Use product-operating-system-scaffold before backfilling the dashboard."
        )
    return projects_root


def skill_root() -> Path:
    return Path(__file__).resolve().parent.parent


def copy_generator(repo_root: Path) -> Path:
    source = skill_root() / "assets" / "repo" / "scripts" / "docs" / "projects-dashboard.mjs"
    if not source.exists():
        raise FileNotFoundError(f"Missing bundled generator asset: {source}")

    destination = repo_root / "scripts" / "docs" / "projects-dashboard.mjs"
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)
    return destination


def patch_package_json(repo_root: Path, docs_root_name: str) -> bool:
    package_json = repo_root / "package.json"
    if not package_json.exists():
        return False

    data = json.loads(package_json.read_text(encoding="utf-8"))
    scripts = data.setdefault("scripts", {})
    command = f"node scripts/docs/projects-dashboard.mjs {docs_root_name}"
    if scripts.get("docs:projects-dashboard") == command:
        return False

    scripts["docs:projects-dashboard"] = command
    package_json.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return True


def patch_projects_readme(projects_root: Path) -> bool:
    readme = projects_root / "README.md"
    if not readme.exists():
        return False

    existing = readme.read_text(encoding="utf-8")
    if "(./dashboard.html)" in existing:
        return False

    if "(./dashboard.md)" in existing:
        updated = existing.replace("(./dashboard.md)", "(./dashboard.html)")
        readme.write_text(updated, encoding="utf-8")
        return True

    addition = "\n\n## Dashboard\n\n- [Project Dashboard](./dashboard.html) - generated portfolio view across all lifecycle lanes.\n"
    readme.write_text(existing.rstrip() + addition, encoding="utf-8")
    return True


def install_content_calendar_templates(docs_root: Path) -> list[Path]:
    source_root = skill_root() / "assets" / "repo" / "docs" / "content"
    if not source_root.exists():
        raise FileNotFoundError(f"Missing bundled content calendar templates: {source_root}")

    destination_root = docs_root / "content"
    destination_root.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    for source in sorted(source_root.iterdir()):
        if not source.is_file():
            continue
        destination = destination_root / source.name
        if destination.exists():
            continue
        shutil.copyfile(source, destination)
        written.append(destination)

    return written


def verify_dashboard_write_is_safe(projects_root: Path, force_dashboard: bool) -> None:
    dashboard = projects_root / "dashboard.html"
    if not dashboard.exists() or force_dashboard:
        return

    preview = dashboard.read_text(encoding="utf-8")[:500]
    if DASHBOARD_MARKER not in preview:
        raise RuntimeError(
            "PROJECTS/dashboard.html already exists but is not marked as generated by docs-project-dashboard. "
            "Re-run with --force-dashboard only if you intend to replace it."
        )


def cleanup_legacy_markdown_dashboard(projects_root: Path) -> bool:
    legacy_dashboard = projects_root / "dashboard.md"
    if not legacy_dashboard.exists():
        return False

    preview = legacy_dashboard.read_text(encoding="utf-8")[:500]
    if DASHBOARD_MARKER not in preview:
        return False

    legacy_dashboard.unlink()
    return True


def run_command(command: list[str], cwd: Path) -> None:
    try:
        subprocess.run(command, cwd=cwd, check=True)
    except FileNotFoundError as exc:
        missing = command[0]
        raise RuntimeError(f"Required executable not found while running {' '.join(command)}: {missing}") from exc


def regenerate_dashboard(repo_root: Path, docs_root_name: str) -> None:
    run_command(["node", "scripts/docs/projects-dashboard.mjs", docs_root_name], cwd=repo_root)

    manifest_script = repo_root / "scripts" / "docs" / "manifest.mjs"
    if manifest_script.exists():
        run_command(["node", "scripts/docs/manifest.mjs", docs_root_name], cwd=repo_root)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Backfill a docs-native project dashboard into an existing repo.")
    parser.add_argument("--repo", required=True, help="Absolute path to the target repository root.")
    parser.add_argument("--docs-root", help="Explicit docs root name, for example DOCS or docs.")
    parser.add_argument(
        "--force-dashboard",
        action="store_true",
        help="Allow replacing an existing PROJECTS/dashboard.html even when it is not marked as generated.",
    )
    parser.add_argument(
        "--with-content-calendar",
        action="store_true",
        help="Install starter docs/content/content-calendar.{json,md} files that the dashboard will surface when present.",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    repo_root = Path(args.repo).expanduser().resolve()
    if not repo_root.is_dir():
        print(f"Repository root not found: {repo_root}", file=sys.stderr)
        return 1

    try:
        docs_root = discover_docs_root(repo_root, args.docs_root)
        projects_root = ensure_projects_root(docs_root)
        verify_dashboard_write_is_safe(projects_root, args.force_dashboard)
        legacy_dashboard_removed = cleanup_legacy_markdown_dashboard(projects_root)
        generator_path = copy_generator(repo_root)
        content_calendar_files = install_content_calendar_templates(docs_root) if args.with_content_calendar else []
        package_json_updated = patch_package_json(repo_root, docs_root.name)
        readme_updated = patch_projects_readme(projects_root)
        regenerate_dashboard(repo_root, docs_root.name)
    except Exception as exc:  # noqa: BLE001
        print(str(exc), file=sys.stderr)
        return 1

    print(f"Docs root: {docs_root}")
    print(f"Projects root: {projects_root}")
    print(f"Generator installed: {generator_path}")
    print(f"package.json updated: {'yes' if package_json_updated else 'no'}")
    print(f"PROJECTS/README.md updated: {'yes' if readme_updated else 'no'}")
    print(
        "Content calendar templates installed: "
        + (", ".join(str(path) for path in content_calendar_files) if content_calendar_files else "no")
    )
    print(f"Legacy dashboard.md removed: {'yes' if legacy_dashboard_removed else 'no'}")
    print("Dashboard regenerated: yes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
