#!/usr/bin/env python3
"""Prepare Claude Code repo config from Codex-style instruction files."""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List

DEFAULT_SOURCE_CANDIDATES = [
    "AGENTS.md",
    ".github/copilot-instructions.md",
]

DEFAULT_ALLOW_COMMANDS = [
    "Bash(rg *)",
    "Bash(ls *)",
    "Bash(cat *)",
    "Bash(head *)",
    "Bash(tail *)",
    "Bash(sed *)",
    "Bash(awk *)",
    "Bash(find *)",
    "Bash(git status*)",
    "Bash(git diff*)",
    "Bash(git log*)",
    "Bash(git show*)",
    "Bash(git add*)",
    "Bash(git commit*)",
    "Bash(pytest*)",
    "Bash(npm test*)",
]

DEFAULT_ASK_COMMANDS = [
    "Bash(git push*)",
    "Bash(git merge*)",
    "Bash(gh pr merge*)",
]

DEFAULT_DENY_COMMANDS = [
    "Bash(git reset --hard*)",
    "Bash(git clean -fd*)",
    "Bash(git checkout --*)",
    "Bash(rm -rf /*)",
    "Bash(rm -rf ~/*)",
]

KEYWORD_PATTERN = re.compile(
    r"\b(always|never|must|must not|should|do not|don't|prefer|avoid|required|forbidden)\b",
    flags=re.IGNORECASE,
)


def die(message: str, code: int = 1) -> None:
    print(f"Error: {message}", file=sys.stderr)
    raise SystemExit(code)


def normalize_repo_path(path: str) -> Path:
    repo = Path(path).expanduser().resolve()
    if not repo.exists() or not repo.is_dir():
        die(f"Repository path is not a directory: {repo}")
    return repo


def normalize_source_path(repo: Path, raw: str) -> Path:
    candidate = Path(raw).expanduser()
    source = candidate if candidate.is_absolute() else (repo / candidate)
    source = source.resolve()
    if source != repo and repo not in source.parents:
        die(f"Source file must be inside repo: {raw}")
    if not source.exists() or not source.is_file():
        die(f"Source file not found: {raw}")
    return source


def discover_sources(repo: Path, explicit_sources: List[str]) -> List[Path]:
    if explicit_sources:
        return [normalize_source_path(repo, raw) for raw in explicit_sources]

    discovered: List[Path] = []
    for rel in DEFAULT_SOURCE_CANDIDATES:
        path = repo / rel
        if path.exists() and path.is_file():
            discovered.append(path.resolve())

    if discovered:
        return discovered

    for path in sorted(repo.rglob("AGENTS.md")):
        if "/.git/" in str(path):
            continue
        discovered.append(path.resolve())

    if discovered:
        return discovered

    die(
        "No Codex instruction sources found. Add AGENTS.md or pass --source <path> explicitly."
    )


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def extract_rules(text: str) -> List[str]:
    results: List[str] = []
    seen = set()
    in_code_block = False

    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()

        if stripped.startswith("```"):
            in_code_block = not in_code_block
            continue
        if in_code_block:
            continue
        if not stripped:
            continue
        if stripped.startswith("#"):
            continue

        candidate = stripped
        if stripped.startswith(("- ", "* ")):
            candidate = stripped[2:].strip()
        elif re.match(r"^\d+\.\s+", stripped):
            candidate = re.sub(r"^\d+\.\s+", "", stripped).strip()

        if len(candidate) > 240:
            continue
        if not KEYWORD_PATTERN.search(candidate):
            continue

        candidate = re.sub(r"`", "", candidate)
        candidate = re.sub(r"\\s+", " ", candidate).strip()
        key = candidate.lower()
        if key in seen:
            continue

        seen.add(key)
        results.append(candidate)

    return results[:40]


def relative_paths(repo: Path, paths: Iterable[Path]) -> List[str]:
    return [str(path.relative_to(repo)).replace("\\\\", "/") for path in paths]


def build_claude_md(source_rel_paths: List[str]) -> str:
    imports = "\n".join(f"@{rel}" for rel in source_rel_paths)
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"""# Claude Code Project Instructions

This repository is configured for Claude Code using Codex parity files.
The canonical instruction sources are imported below and should stay authoritative.

Generated by `setup_claude_repo.py` on {generated}.

## Imported instruction sources
{imports}
@.claude/rules/00-codex-parity.md

## Behavior defaults
- Follow imported instruction files as strict policy.
- Prefer non-interactive commands and deterministic scripts.
- Prefer `rg` for text/file discovery when available.
- Refuse destructive commands unless explicitly requested by the user.
- Keep edits minimal, scoped, and verifiable.
"""


def build_rules_md(source_rel_paths: List[str], extracted_rules: List[str]) -> str:
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    source_list = "\n".join(f"- `{rel}`" for rel in source_rel_paths)

    if extracted_rules:
        rule_lines = "\n".join(f"- {rule}" for rule in extracted_rules)
    else:
        rule_lines = "\n".join(
            [
                "- Follow AGENTS.md and imported instruction files as canonical policy.",
                "- Prefer `rg` for searching files/text when available.",
                "- Avoid destructive git/file-system commands unless explicitly requested.",
                "- Keep changes minimal and validate with focused checks.",
            ]
        )

    return f"""# Codex Parity Rules

This rules file mirrors key policy-style instructions from Codex repo guidance.
Generated by `setup_claude_repo.py` on {generated}.

## Sources
{source_list}

## Extracted policy rules
{rule_lines}

## Maintenance
- Re-run `setup_claude_repo.py --repo <path> --force` after changing source instruction files.
"""


def build_settings_json() -> str:
    payload = {
        "permissions": {
            "defaultMode": "acceptEdits",
            "disableBypassPermissionsMode": "disable",
            "allow": DEFAULT_ALLOW_COMMANDS,
            "ask": DEFAULT_ASK_COMMANDS,
            "deny": DEFAULT_DENY_COMMANDS,
        }
    }
    return json.dumps(payload, indent=2) + "\n"


def write_file(path: Path, content: str, force: bool, dry_run: bool) -> str:
    if path.exists() and not force:
        return "skipped"

    if dry_run:
        return "planned"

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return "written"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Prepare CLAUDE.md, .claude/rules, and .claude/settings.json from Codex instructions."
    )
    parser.add_argument(
        "--repo",
        default=".",
        help="Path to the repository root (default: current directory)",
    )
    parser.add_argument(
        "--source",
        action="append",
        default=[],
        help="Instruction file path inside repo (repeatable). Defaults to AGENTS.md discovery.",
    )
    parser.add_argument(
        "--skip-settings",
        action="store_true",
        help="Skip writing .claude/settings.json.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing generated files.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written without changing files.",
    )

    args = parser.parse_args()
    repo = normalize_repo_path(args.repo)
    source_paths = discover_sources(repo, args.source)
    source_rel_paths = relative_paths(repo, source_paths)

    merged_text = "\n\n".join(read_text(path) for path in source_paths)
    extracted_rules = extract_rules(merged_text)

    claude_md_path = repo / "CLAUDE.md"
    rules_path = repo / ".claude" / "rules" / "00-codex-parity.md"
    settings_path = repo / ".claude" / "settings.json"

    results = []
    results.append(
        (
            claude_md_path,
            write_file(
                claude_md_path,
                build_claude_md(source_rel_paths),
                force=args.force,
                dry_run=args.dry_run,
            ),
        )
    )
    results.append(
        (
            rules_path,
            write_file(
                rules_path,
                build_rules_md(source_rel_paths, extracted_rules),
                force=args.force,
                dry_run=args.dry_run,
            ),
        )
    )

    if not args.skip_settings:
        results.append(
            (
                settings_path,
                write_file(
                    settings_path,
                    build_settings_json(),
                    force=args.force,
                    dry_run=args.dry_run,
                ),
            )
        )

    print(f"Repo: {repo}")
    print("Sources:")
    for rel in source_rel_paths:
        print(f"- {rel}")

    print("\nOutputs:")
    for path, state in results:
        rel = path.relative_to(repo)
        print(f"- {rel}: {state}")


if __name__ == "__main__":
    main()
