// This file is generated by scripts/build_docs_site_catalog.py. Do not hand-edit.
import type { CatalogItem } from './catalog-types';

export const catalog = {
  "generatedBy": "scripts/build_docs_site_catalog.py",
  "skillCount": 20,
  "pluginCount": 2,
  "items": [
    {
      "slug": "ml-catalog-review",
      "kind": "skill",
      "title": "Catalog Review",
      "folder": "ML-catalog-review",
      "status": "active",
      "summary": "Run numbered Shopify-first catalog review workflows",
      "description": "Standard Shopify-first catalog review workflow for opening a numbered project, generating numbered JPG review boards with optional PDF bundles, collecting human corrections, and translating that feedback into apply/verify passes with evidence artifacts. Use when asked to create catalog review boards, set up a catalog cleanup project, review missing colors/orientations/subjects, prepare a merchandising review packet, or apply catalog review corrections.",
      "category": "Storefront and commerce",
      "path": "skills/ML-catalog-review",
      "resources": [
        "agent metadata"
      ],
      "useCases": [
        "Create catalog review boards",
        "Set up a catalog cleanup project",
        "Review missing colors/orientations/subjects",
        "Prepare a merchandising review packet",
        "Apply catalog review corrections"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-cluster-assignment",
      "kind": "skill",
      "title": "Cluster Assignment",
      "folder": "ML-cluster-assignment",
      "status": "active",
      "summary": "Plan and bootstrap parallel work clusters",
      "description": "Split repository work into dependency-safe parallel clusters, then bootstrap branches/worktrees, GitHub tracking issues, and ready-to-run agent prompts. Use when a user asks to run multiple agents in parallel or wants branch/worktree cluster setup.",
      "category": "Repository setup",
      "path": "skills/ML-cluster-assignment",
      "resources": [
        "bundled scripts",
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "Run multiple agents in parallel",
        "Branch/worktree cluster setup"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-codex-to-claude-handoff",
      "kind": "skill",
      "title": "Codex to Claude Handoff",
      "folder": "ML-codex-to-claude-handoff",
      "status": "active",
      "summary": "Mirror Codex rules into Claude setup + docs",
      "description": "Prepare a repository for Claude Code Desktop by generating CLAUDE.md, .claude/rules/*.md, and .claude/settings.json from existing Codex instruction files (especially AGENTS.md and .github/copilot-instructions.md). Use when migrating or handing off a repo from Codex to Claude while preserving operating rules and safety guardrails.",
      "category": "Repository setup",
      "path": "skills/ML-codex-to-claude-handoff",
      "resources": [
        "bundled scripts",
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "Migrating",
        "Handing off a repo from Codex to Claude while preserving operating rules and safety guardrails"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-collaborative-walkthrough",
      "kind": "skill",
      "title": "Collaborative Walkthrough",
      "folder": "ML-collaborative-walkthrough",
      "status": "active",
      "summary": "Run Q&A walkthrough on in-review projects",
      "description": "Run a structured Q&A walkthrough for in-review project streams in repos with standardized docs scaffolding. Use when a user asks for collaborative walkthrough, sign-off review, or readiness check before moving projects to completed.",
      "category": "Delivery governance",
      "path": "skills/ML-collaborative-walkthrough",
      "resources": [
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "A user asks for collaborative walkthrough",
        "Sign-off review",
        "Readiness check before moving projects to completed"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-continue-until-blocked",
      "kind": "skill",
      "title": "Continue Until Blocked",
      "folder": "ML-continue-until-blocked",
      "status": "active",
      "summary": "Run autonomously until cutover or blocker",
      "description": "Execute already-scoped repository work autonomously until the cutover is complete or a true blocker requires user input. Use when the user says to keep going without intervention, continue until blocked, finish the cutover, or otherwise hand the thread continuous execution authority. Assume the current thread already understands the repository and approved scope, and assume project docs follow the standard docs scaffolding with governance files and status-based project docs.",
      "category": "Delivery governance",
      "path": "skills/ML-continue-until-blocked",
      "resources": [
        "agent metadata"
      ],
      "useCases": [
        "The user says to keep going without intervention",
        "Continue until blocked",
        "Finish the cutover",
        "Otherwise hand the thread continuous execution authority. Assume the current thread already understands the repository and approved scope",
        "Assume project docs follow the standard docs scaffolding with governance files and status-based project docs"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-docs-evidence-backfill",
      "kind": "skill",
      "title": "Docs Evidence Backfill",
      "folder": "ML-docs-evidence-backfill",
      "status": "active",
      "summary": "Retrofit an existing repo onto a unified docs evidence system",
      "description": "Retrofit an existing repository from fragmented audit and artifact storage into a unified docs evidence system. Use when an existing repo has evidence spread across places like docs assets, review-board folders, repo-root artifacts, tmp folders, or legacy generated outputs and needs a canonical docs-root evidence structure such as `DOCS/evidence/` or `docs/evidence/` plus path/reference cleanup.",
      "category": "Documentation systems",
      "path": "skills/ML-docs-evidence-backfill",
      "resources": [
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "An existing repo has evidence spread across places like docs assets",
        "Review-board folders",
        "Repo-root artifacts",
        "Tmp folders",
        "Legacy generated outputs and needs a canonical docs-root evidence structure such as `DOCS/evidence/`"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-docs-product-pack",
      "kind": "skill",
      "title": "Product Docs Pack (Deprecated)",
      "folder": "ML-docs-product-pack",
      "status": "deprecated",
      "summary": "Deprecated; redirects to Docs System Scaffold",
      "description": "Deprecated shim. Use `ML-docs-system-scaffold` for product-doc scaffolding and docs governance/tooling in one workflow.",
      "category": "Delivery governance",
      "path": "skills/ML-docs-product-pack",
      "resources": [
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "Run Product Docs Pack (Deprecated) when its workflow matches the repo outcome you need.",
        "Use it after the target repo has enough context for Codex to act safely."
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-docs-project-dashboard-legacy",
      "kind": "skill",
      "title": "Docs Project Dashboard (Legacy)",
      "folder": "ML-docs-project-dashboard-legacy",
      "status": "active",
      "summary": "Deprecated standalone backfill for the HTML dashboard",
      "description": "Deprecated standalone backfill for a generated HTML project-management dashboard in repositories that already use the ML-docs-system-scaffold `PROJECTS/` lifecycle structure. Prefer the built-in optional dashboard step in `$ML-docs-system-scaffold`. Use this legacy skill only when patching an existing repo without rerunning the main scaffold flow.",
      "category": "Delivery governance",
      "path": "skills/ML-docs-project-dashboard-legacy",
      "resources": [
        "bundled scripts",
        "reference guides",
        "starter assets",
        "agent metadata"
      ],
      "useCases": [
        "Run Docs Project Dashboard (Legacy) when its workflow matches the repo outcome you need.",
        "Use it after the target repo has enough context for Codex to act safely."
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-docs-project-lifecycle-statuses",
      "kind": "skill",
      "title": "Docs Lifecycle Statuses (Legacy)",
      "folder": "ML-docs-project-lifecycle-statuses",
      "status": "legacy",
      "summary": "Legacy retrofit for in-review/blocked project lifecycle states",
      "description": "Transitional legacy patch for repositories that were scaffolded before ML-docs-system-scaffold included `in-review` and `blocked` lifecycle states. Use only to retrofit those states and synchronized governance updates across project docs and instruction files.",
      "category": "Delivery governance",
      "path": "skills/ML-docs-project-lifecycle-statuses",
      "resources": [
        "bundled scripts",
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "Run Docs Lifecycle Statuses (Legacy) when its workflow matches the repo outcome you need.",
        "Use it after the target repo has enough context for Codex to act safely."
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-docs-system-scaffold",
      "kind": "skill",
      "title": "Docs System Scaffold",
      "folder": "ML-docs-system-scaffold",
      "status": "active",
      "summary": "Scaffold docs governance, evidence storage, and optional ecommerce review workflow",
      "description": "Scaffold or standardize a repository documentation system (DOCS/ or docs), optionally scaffold a VitePress docs site, install docs tooling, include an optional lightweight product-doc pack, optionally scaffold an HTML project dashboard over the `PROJECTS/` lifecycle tree, and optionally add an ecommerce ML-catalog-review operating pattern. Use when asked for docs system setup, docs IA cleanup, docs governance hardening, product docs scaffolding, docs-site setup, a repo-native planning dashboard, or ecommerce ML-catalog-review project scaffolding.",
      "category": "Storefront and commerce",
      "path": "skills/ML-docs-system-scaffold",
      "resources": [
        "bundled scripts",
        "reference guides",
        "starter assets",
        "agent metadata"
      ],
      "useCases": [
        "Asked for docs system setup",
        "Docs IA cleanup",
        "Docs governance hardening",
        "Product docs scaffolding",
        "Docs-site setup"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-env-bootstrap-sync",
      "kind": "skill",
      "title": "Env Bootstrap Sync",
      "folder": "ML-env-bootstrap-sync",
      "status": "active",
      "summary": "Help with env sync and bootstrap workflows",
      "description": "Create or upgrade a repo-owned environment bootstrap workflow with reproducible `.env` handling, worktree sync, required-variable documentation, secret-file layout, and new-machine runbooks. Use when a repo has drifting `.env` files, unclear setup requirements, worktree-specific config loss, or scattered credential/bootstrap instructions.",
      "category": "Documentation systems",
      "path": "skills/ML-env-bootstrap-sync",
      "resources": [
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "A repo has drifting `.env` files",
        "Unclear setup requirements",
        "Worktree-specific config loss",
        "Scattered credential/bootstrap instructions"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-github-docs-tracking-sync",
      "kind": "skill",
      "title": "GitHub Docs Tracking Sync (Optional)",
      "folder": "ML-github-docs-tracking-sync",
      "status": "active",
      "summary": "On-demand docs-to-GitHub sync; do not run by default",
      "description": "Optional docs-to-GitHub tracking sync (1027-style). Prefer manual/targeted use only when explicitly requested.",
      "category": "Documentation systems",
      "path": "skills/ML-github-docs-tracking-sync",
      "resources": [
        "bundled scripts",
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "Run GitHub Docs Tracking Sync (Optional) when its workflow matches the repo outcome you need.",
        "Use it after the target repo has enough context for Codex to act safely."
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-hyphenomenon-project-intake",
      "kind": "skill",
      "title": "Hyphenomenon Intake",
      "folder": "ML-hyphenomenon-project-intake",
      "status": "active",
      "summary": "Build project intake dossier + screenshots",
      "description": "Create a Hyphenomenon import-ready project intake package (single markdown dossier plus 4-8 screenshots) for a software repository. Use when a user asks to prepare a repo for import as a project + graph nodes, especially when they require exact dossier section headers, screenshot gallery links, hydration artifacts, workflow summaries, and a handoff checklist.",
      "category": "Delivery governance",
      "path": "skills/ML-hyphenomenon-project-intake",
      "resources": [
        "bundled scripts",
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "Prepare a repo for import as a project + graph nodes",
        "Especially when they require exact dossier section headers",
        "Screenshot gallery links",
        "Hydration artifacts",
        "Workflow summaries"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-plan-signoff-review",
      "kind": "skill",
      "title": "Plan Signoff Review",
      "folder": "ML-plan-signoff-review",
      "status": "active",
      "summary": "Re-read the full thread and latest audits before plan approval",
      "description": "Review a proposed final plan against the full current thread and the latest supporting audits, reports, and decision artifacts before approval. Use when the user asks to double-check that a plan reflects everything discussed, incorporates the newest review documents, or needs a final readiness pass in an existing Plan mode thread.",
      "category": "Delivery governance",
      "path": "skills/ML-plan-signoff-review",
      "resources": [
        "agent metadata"
      ],
      "useCases": [
        "The user asks to double-check that a plan reflects everything discussed",
        "Incorporates the newest review documents",
        "Needs a final readiness pass in an existing Plan mode thread"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-project-governance-audit",
      "kind": "skill",
      "title": "Project Governance Audit",
      "folder": "ML-project-governance-audit",
      "status": "active",
      "summary": "Audit project docs, checkpoint hygiene, and roadmap ordering",
      "description": "Run a governance audit across project planning docs and roadmap artifacts. Use for blocker/dependency/order analysis, strategy consistency checks, and checkpoint-quality enforcement with file-backed evidence.",
      "category": "Delivery governance",
      "path": "skills/ML-project-governance-audit",
      "resources": [
        "agent metadata"
      ],
      "useCases": [
        "Run Project Governance Audit when its workflow matches the repo outcome you need.",
        "Use it after the target repo has enough context for Codex to act safely."
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-project-tranche-orchestrator",
      "kind": "skill",
      "title": "Project Tranche Orchestrator",
      "folder": "ML-project-tranche-orchestrator",
      "status": "active",
      "summary": "Primary-agent tranche planning, delegation, review, and docs writeback in collaborative or autonomous mode.",
      "description": "Act as the primary project manager and agent orchestrator for repos using the standard docs scaffold. Use when the user wants one primary agent to read project docs, derive the next tranche, delegate bounded work to subagents, manage handoffs, review completion, and write status updates back into the existing docs without creating a second source of truth.",
      "category": "Delivery governance",
      "path": "skills/ML-project-tranche-orchestrator",
      "resources": [
        "bundled scripts",
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "The user wants one primary agent to read project docs",
        "Derive the next tranche",
        "Delegate bounded work to subagents",
        "Manage handoffs",
        "Review completion"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-repo-implementation-review",
      "kind": "skill",
      "title": "Repo Implementation Review",
      "folder": "ML-repo-implementation-review",
      "status": "active",
      "summary": "Compare 2-3 repos and generate a review report",
      "description": "Review and compare 2-3 repositories that implement the same product idea, then generate a downloadable HTML comparison artifact with pros/cons, feature gaps, scores, recommendation paths, and CSV/PDF export options. Use when a user asks for side-by-side technical assessment of multiple implementation repos or wants a recommendation between competing codebases.",
      "category": "Documentation systems",
      "path": "skills/ML-repo-implementation-review",
      "resources": [
        "bundled scripts",
        "reference guides",
        "starter assets",
        "agent metadata"
      ],
      "useCases": [
        "A user asks for side-by-side technical assessment of multiple implementation repos",
        "A recommendation between competing codebases"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-shopify-app-scaffold",
      "kind": "skill",
      "title": "Shopify App Scaffold",
      "folder": "ML-shopify-app-scaffold",
      "status": "active",
      "summary": "Create a fresh Shopify app shell with reusable comms and review modules",
      "description": "Scaffold a new Shopify app from the latest installed Shopify CLI template, then layer in a reusable shell for merchant email opt-in, unsubscribe flow, review prompts, and optional billing/app-proxy/theme-extension placeholders. Use when creating a new Shopify app quickly without copying an old repo wholesale.",
      "category": "Storefront and commerce",
      "path": "skills/ML-shopify-app-scaffold",
      "resources": [
        "bundled scripts",
        "reference guides",
        "starter assets",
        "agent metadata"
      ],
      "useCases": [
        "Creating a new Shopify app quickly without copying an old repo wholesale"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-user-journey-audit",
      "kind": "skill",
      "title": "User Journey Audit",
      "folder": "ML-user-journey-audit",
      "status": "active",
      "summary": "Audit user journeys and export PDF",
      "description": "Create current-state user journey audits with route mapping, screenshots, coverage verification, and a final PDF report. Use when Codex needs to audit navigation or UX flows for one or more user types in any repository or deployed app, suggest which user types to include, capture click-by-click evidence, verify route coverage against code and tests, and export a screenshot-backed PDF artifact.",
      "category": "Documentation systems",
      "path": "skills/ML-user-journey-audit",
      "resources": [
        "bundled scripts",
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "Codex needs to audit navigation",
        "UX flows for one",
        "More user types in any repository",
        "Deployed app",
        "Suggest which user types to include"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "ml-ux-ui-bug-intake",
      "kind": "skill",
      "title": "ML-ux-ui-bug-intake",
      "folder": "ML-ux-ui-bug-intake",
      "status": "active",
      "summary": "Set up a lightweight UX/UI bug intake system with lifecycle docs, routing rules, and routines.",
      "description": "Set up a lightweight UX/UI bug intake system with lifecycle docs, routing rules, and routines. Use when starting a new project stream, standardizing repo operations, or replacing ad hoc bug tracking with a simple docs-backed workflow.",
      "category": "Delivery governance",
      "path": "skills/ML-ux-ui-bug-intake",
      "resources": [
        "bundled scripts",
        "reference guides",
        "agent metadata"
      ],
      "useCases": [
        "Starting a new project stream",
        "Standardizing repo operations",
        "Replacing ad hoc bug tracking with a simple docs-backed workflow"
      ],
      "gettingStarted": [
        "Copy the complete skill folder into the Codex skills location used by your team.",
        "Open the target repo and read its local agent instructions before invoking the skill.",
        "Name the outcome you want, the repo constraints, and any files or routes Codex should avoid.",
        "Review generated scripts, docs, or code before adopting them into the customer's workflow."
      ],
      "troubleshooting": [
        "If Codex does not trigger the skill, invoke it by name and include the target repo outcome.",
        "If the output has the wrong audience, explicitly say whether the deliverable is customer-facing or repo-internal.",
        "If a bundled script fails, run it from the target repo root and confirm the full skill folder was copied intact."
      ]
    },
    {
      "slug": "design-system-first",
      "kind": "plugin",
      "title": "Design System First",
      "folder": "design-system-first",
      "status": "available",
      "summary": "Create opinionated Next.js starters with a reusable design system.",
      "description": "Scaffold greenfield Next.js projects with shared tokens, shadcn foundations, strong starter surfaces, and optional docs or testing overlays.",
      "category": "Developer Tools",
      "path": "plugins/design-system-first",
      "resources": [
        "Interactive capability",
        "Write capability"
      ],
      "useCases": [
        "Create a new design-system-first marketing site starter.",
        "Scaffold an app-shell starter with docs and testing enabled.",
        "Refine this starter's tokens, hierarchy, and surfaces."
      ],
      "gettingStarted": [
        "Install the complete plugin folder from the delivered pack or repo-local backup.",
        "Refresh Codex so plugin skills, metadata, assets, and default prompts are visible.",
        "Start from one suggested prompt, then add the target repo path and desired deliverable."
      ],
      "troubleshooting": [
        "If the plugin does not appear, confirm .codex-plugin/plugin.json is present and the plugin registry points to the folder.",
        "If a plugin skill cannot find scripts or assets, the plugin folder was likely flattened or partially copied.",
        "If the workflow is too broad, rerun with a narrower deliverable and explicit no-touch files."
      ]
    },
    {
      "slug": "project-tranche-orchestrator",
      "kind": "plugin",
      "title": "Project Tranche Orchestrator",
      "folder": "project-tranche-orchestrator",
      "status": "available",
      "summary": "Derive, delegate, review, and document one tranche through a single primary agent in collaborative or autonomous mode.",
      "description": "Reads standardized project docs, derives the next executable tranche, optionally collaborates with the user before delegation, delegates bounded work to subagents, enforces a doc-and-code review gate, and writes status updates back into the existing governance docs without creating a second source of truth.",
      "category": "Productivity",
      "path": "plugins/project-tranche-orchestrator",
      "resources": [
        "Interactive capability",
        "Write capability",
        "Multi-Agent capability"
      ],
      "useCases": [
        "Orchestrate the next tranche from this repo's project docs in collaborative mode.",
        "Review the current tranche and tell me if it is ready to advance.",
        "Split the next tranche into safe subagent assignments."
      ],
      "gettingStarted": [
        "Install the complete plugin folder from the delivered pack or repo-local backup.",
        "Refresh Codex so plugin skills, metadata, assets, and default prompts are visible.",
        "Start from one suggested prompt, then add the target repo path and desired deliverable."
      ],
      "troubleshooting": [
        "If the plugin does not appear, confirm .codex-plugin/plugin.json is present and the plugin registry points to the folder.",
        "If a plugin skill cannot find scripts or assets, the plugin folder was likely flattened or partially copied.",
        "If the workflow is too broad, rerun with a narrower deliverable and explicit no-touch files."
      ]
    }
  ]
} as const satisfies {
  generatedBy: string;
  skillCount: number;
  pluginCount: number;
  items: readonly CatalogItem[];
};
